name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Amir Fatemi blog, where he posts his blog stuff"

markdown: kramdown
highlighter: rouge
#logo: false
paginate: 15
baseurl: ""
#domain_name: "https://fatemi.blog"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Amir Fatemi"

# Disqus config
disqus-shortname: ""
